import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Footer from "./_components/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "AI-Trip-Planner",
  description: "Generated by create next app",
  icons: {
    icon: "/travel2.png",
    shortcut: "/travel2.png",
    apple: "/travel2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.variable} antialiased`}
        >
          <ConvexClientProvider>{children}</ConvexClientProvider>
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}
